; Project upload / evaluation
upload_max_filesize = 64M
post_max_size = 128M
max_file_uploads = 2000
max_execution_time = 300
max_input_time = 300
max_input_vars = 5000
display_errors = Off
log_errors = On
